---
title: "Exercise 6.3"
subtitle: "An Economy With Periodic Interest-Rate Shocks"
---
<a class="return-button" href="index.qmd">⬅ Return</a>

## Problem

A perfect-foresight
small open economy is inhabited by identical consumers with preferences of the form

$$
\sum_{t=0}^{\infty}\beta^t \ln(c_t),
$$

where $c_t$ denotes consumption of a perishable good, and $\beta\in(0,1)$ denotes the discount factor. Households are subject to the budget constraint

$$
d_t = (1+r_{t-1})d_{t-1}  +c_t - y. 
$$

for $t\ge0$, where $d_t$ denotes one-period debt acquired in period $t$ and maturing in $t+1$, $r_t$ denotes the interest paid on $d_t$, and $y$ denotes a constant endowment of consumption goods received each period. Households are subject to the no-Ponzi-game constraint 

$$
\lim_{t\rightarrow \infty}\frac{d_t}{\prod_{s=0}^t(1+r_s)}\le 0.
$$

The initial stock of debt, $d_{-1}$, is nil. The interest  rate is time varying and given by

$$
r_t = \left\{
\begin{array}{ll}
r^H&\mbox{ for } t=0,2,4,\dots\\
r^L&\mbox{ for } t=1,3,5,\dots
\end{array}
\right.,
$$

where $r^L$ and $r^H$ are parameters satisfying $0<r^L<r^H$ and  

$$
\beta \sqrt{(1+r^H)(1+r^L)}=1.
$$

1. Derive the equilibrium path of consumption as a function of the structural parameters of the model, $y$,  $r^H$, $r^L$, and $\beta$. Discuss its cyclical properties. 

2. Characterize the equilibrium behavior of the trade balance, the current account, and external debt. 

3.  Discuss the macroeconomic effects of the assumed interest-rate variations. 

## Answer

Together, the Euler equation $c_{t+1}=\beta (1+r_t) c_t$, the assumed law of motion of $r_t$, and the restriciton $\beta \sqrt{(1+r^L)(1+r^H)}=1$ imply that 

$$
c_t = c_0,
$$

$$
c_{t+1} = c_1,
$$

for $t\ge0$, and 

$$
c_1 = \beta(1+r^H)c_0>c_0. \tag{1}
$$

To determine the quantities $c_0$ and $c_1$, conjecture that 
$$
d_t = d_0
$$

and that 

$$
d_{t+1} = d_1
$$

for $t\ge 0$. To find the quantities $c_0$, $c_1$, $d_0$, and $d_1$, write the sequential budget constraints for periods 0, 1, and 2 to get, respectively (recall that $d_{-1}=0$)

$$
c_0 = y +d_0 \tag{2}
$$

$$
c_1 +(1+r^H)d_0 = y - d_1, \tag{3}
$$

$$
c_0 + (1+r^L)d_1 = y +d_0 \tag{4}
$$

Expressions (2) and (4) imply that 

$$
d_1=0.
$$

This result along with (1) and (3) yield the following solution for the equilibrium level of debt assumed in periods $t=0, 2, \dots$

$$
d_0 =-y \frac{\beta(1+r^H)-1}
{(1+r^H)(1-\beta)}<0
$$

Summarizing,  we deduced that 

\(1\) Consumption is lower  than $y$ in even periods  and higher than $y$ in odd periods.

\(2\) The trade balance is positive  in even periods  and negative in odd periods.

\(3\) Debt is negative in even periods and nil in odd periods.

\(4\) The current account is positive in even periods and negative in odd periods. 

The intuition is that  when the interest rate is high (even periods) it pays to contract consumption and save, and the reverse when the interest rate is low (odd periods). 
