---
title: "Exercise 7.6"
subtitle: "Tariffs And The Effects Of Terms Of Trade Shocks"
---
<a class="return-button" href="index.qmd">⬅ Return</a>

## Problem

Continuing with the theme of the previous two exercises, one possible explanation behind the mismatch between the predictions of the theoretical and empirical models regarding the importance of terms-of-trade shocks is the presence of trade tariffs. To the extent that trade taxes move systematically in the opposite direction as the terms of trade, the domestic relative price of exportables and importables will be insensitive to movements in their world counterparts, which, in turn, may attenuate the effects of terms-of-trade shocks on domestic activity. Continue to assume that $p^x_t$ and $p^m_t$ denote the domestic prices of exportables and importables, respectively, in terms of final goods, and that $tot_t\equiv p^x_t/p^m_t$ denotes the domestic terms of trade. The novelty in the present setting is that there is a tax that introduces a wedge, denoted $\gamma_t$, 
between the domestic and the foreign terms of trade. Specifically, assume that 

$$
tot_t = tot^*_t \gamma_t,
$$

where $tot^*_t$ denotes the foreign terms of trade. The wedge $\gamma_t$ is  one minus a proportional trade barrier, which might take the form of a combination of import and export taxes. As before, the country takes the evolution of the foreign terms of trade as given. Assume that $tot^*_t$  follows the AR(1) process

$$
\ln\left(
\frac{tot^*_t}
{tot^*}\right)
 = \rho \ln
\left(\frac{tot^*_{t-1}}
{tot^*}\right)
 + \pi \epsilon^{tot*}_t,
$$

where $tot^*$ denotes the steady-state value of $tot^*_t$. Assume that the government increases taxes on exports (or reduces taxes on imports) when the foreign terms of trade improves. Specifically, assume that 

$$
\gamma_t = \left(\frac{tot^*_t}{tot^*}\right)^{-\eta},
$$

with $\eta>0$. Finally, assume that the government rebates the proceeds of trade taxes to households in a lump-sum fashion. Calibrate the model using the values for the structural parameters given in Table 7.5 and the cross-country medians of $\rho$, $\pi$, $\phi$, and $\psi$, given in Tables 7.1 and 7.4. Consider different values of $\eta$ ranging from 0 to 1. For each value of $\eta$ compute the variances of output, consumption, investment, and the trade balance due to terms-of-trade shocks. Discuss your results.

## Answer

_To be added._
