---
title: "Exercise 4.4 - Solution"
subtitle: "Complete Asset Markets and a Discrete Endowment Process"
---
<a class="return-button" href="4_4.qmd">⬅ Return</a>

## Problem

Consider an economy populated by a large number of identical consumers with preferences described by the utility function

$$
E_0 \sum_{t=0}^\infty \beta^t U(c_t),
$$

where $c_t$ denotes consumption in period $t$, $\beta \in (0, 1)$ denotes the subjective discount factor, $U(\cdot)$ is a strictly increasing and differentiable function, and $E_t$ denotes the mathematical expectations operator conditional on information available at time $t$. Suppose each consumer starts with an initial financial wealth equal to $b_0$ in period 0, measured in terms of consumption goods. Suppose that each period there are two possible states of nature, H and L, with transition probability matrix

$$
\Pi =
\begin{bmatrix}
\pi_{HH} & \pi_{HL} \\
\pi_{LH} & \pi_{LL}
\end{bmatrix},
$$

where $\pi_{ij}$, for $i, j \in \{H, L\}$, denotes the probability that the state of nature in period $t+1$ is $j$ conditional on the state of nature in period $t$ being $i$, for all $t \geq 0$. The consumer is endowed with $y_t$ units of consumption goods in period $t$, where $y_t$ is a random variable taking the values $y_H$ and $y_L$ in states H and L, respectively, with $y_H > y_L > 0$. Consumers have access to the world financial market, which offers a complete set of state-contingent claims. Let $p_{ij}$ be the price in units of consumption of period $t$ of a state-contingent claim that pays 1 unit of consumption in $t+1$ if the state of nature in period $t+1$ is $j$ conditional on the state of nature in period $t$ being $i$, for $i, j \in \{H, L\}$ and $t \geq 0$. Suppose further that $p_{ij} = \beta \pi_{ij}$. Suppose that the state of nature in period 0 is $H$.

1. State the consumer’s maximization problem.

2. Characterize the equilibrium process of consumption.

3. Characterize the equilibrium process of the trade balance.

4. Characterize the equilibrium process of the net foreign asset position (recall that in period 0 it is known and given by $b_0$).

5. Characterize the equilibrium process of the current account starting in period 1.

6. Compare the equilibrium processes of consumption, the trade balance, and the current account obtained above to those pertaining to another open economy that is identical to the one described above in all respects, except that its initial endowment is $y_L$.

## Answer

#### 1.

Use the notation of Chapter 4.9. 

$$
\max E_0 \sum_{t=0}^{\infty} \beta^t U(c_t)  \quad \mbox{s.t. } \quad c_t + E_tq_{t,t+1} b_{t+1} = y_t + b_t 
$$

given $y_0=y_H$ and $b_0$ and a no-Ponzi game constraint $\lim_{j \rightarrow \infty} E_t q_{t,t+j} b_{t+j}=0$ for all dates and states. 


#### 2.

FOC under complete markets

$$
U'(c_t) q_{t,t+1} = \beta U'(c_{t+1})
$$

In this problem it is given that $q_{t,t+1} = \beta$, thus consumption is constant over dates and states, or  $c_t = c$.  

Multiply budget constraint by $q_{0,t}$, take $E_0$, sum for $t=0$ to $t=T$, 

$$
\sum_{t=0}^{T} q_{0,t} E_0 c_t + E_0q_{0,T+1} b_{T+1} = \sum_{t=0}^{T} q_{0,t} E_0 y_t + b_0 
$$

Take limit for $T\rightarrow \infty$, use no-Ponzi, use $c_t =c$, use $q_{0,t} = \beta^t$: 

$$
\frac{ c}{1-\beta}  = \sum_{t=0}^{\infty}  E_0 \beta^t y_t + b_0 
$$

where $b_0$ is given, $y_0 = y_H$, and $E_0 \sum_{t=0}^{\infty}  E_0 \beta^t y_t  = Y^H \equiv \left[\begin{array}{cc}1 & 0\end{array}\right] [I-\beta \Pi]^{-1} \left[\begin{array}{cc} y_H & y_L\end{array}\right]'$

Note that the present value budget constraint  must also hold at any future date, that is, for any date $t>0$ and any state (high or low) it must be that 

$$
\frac{ c}{1-\beta}  = \sum_{j=0}^{\infty}  E_t \beta^j y_{t+j} + b_t 
$$

Notice that $ \sum_{j=0}^{\infty}  E_t \beta^j y_{t+j}$ takes only  2 values, $Y^H$ or 
$Y^L\equiv  \left[\begin{array}{cc}0 & 1 \end{array}\right] [I-\beta \Pi]^{-1} \left[ \begin{array}{cc} y_H & y_L\end{array}\right]'$ depending on whether the current state is $H$ or $L$. It follows that $b_t$ also only takes two values, either $b_H\equiv \frac{ c}{1-\beta} - Y^H$ or $b_L \equiv \frac{ c}{1-\beta} - Y^L$. Note that $b_H<b_L$, which means that contingent claim pays less in the state H than in the state L. Furthermore, evaluating the present value budget constraint in period 0, we see that $b_0=b_H$.

#### 3.

Trade balance in period t: $tb_t = y_t -c$. When $y_t=y_H$,  $tb_t = y_H - c$ and when $y_t = y_L$, then $tb_t = y_L-c$, which means that the trade balance is procyclical.  

#### 4.

Using the notation of  section 4.9.1, we denote the net foreign asset position in period $t$ as $s_t = E_tq_{t,t+1} b_{t+1}= \beta E_t b_{t+1}$. Since $b_t$ takes only 2 values, we have $\left[\begin{array}{cc} s_H & s_L\end{array}\right]' = \beta \Pi \left[\begin{array}{cc} b_H & b_L\end{array}\right]' $

#### 5.

The current account is $ca_t = s_t - s_{t-1}$. If the states in period $t-1$ and period $t$ are the same, the current account in period $t$ is zero. If the state in period $t-1$ was $y_L$ and in period $t$ it is $y_H$, then $ca_t = s_H-s_L>0$. And if in period $t-1$, the state was $y_H$ and in period $t$ the state is $y_L$, then $ca_t = s_L -s_H<0$. This is intuitive. If the state is $y_H$ and was $y_L$ before, then the country should run a current account surplus as it accumulates net foreign assets. At the same time, if in the current period the endowment is low,  $y_L$, but was high in the previous period, $y_H$, then the country should run a current account deficit ie running down its stock of net foreign assets. This behavior of the current account is a consequence market completeness. Getting a high realization of the endowment in period $t$ has no effect on future consumption as the windfall was already fully insured. 

#### 6.

Now assume that the state in period $0$ is $L$ and the initial asset position is the same, namely, $b_0$.  Let a hat over the variable denote the equilibrium. Then we have 
$\hat{c}/(1-\beta) = Y^L +b_0$. Because $Y^L< Y^H$, $\hat{c}<c$, so consumption is constant but lower. $\hat{tb}_H = y_H-\hat{c} >tb_H$ and $\hat{tb}_L = y_L-\hat{c} >tb_L$. Now $\hat{b}_L= b_0=b_H<b_L$ and $\hat{b}_H= \hat{c}/(1-\beta) -Y^H<b_H=b_0$This means that contingent claims are now less in both states. This makes sense because the initial present value of this economy is lower by $Y^H-Y^L$.  What are net foreign assets? 

$$
\left[\begin{array}{cc}
\hat{s}_H &
\hat{s}_L\end{array}\right]' = \beta \Pi 
\left[\begin{array}{cc}
\hat{b}_H &
\hat{b}_L\end{array}\right]'
$$

So $\hat{s}_H<s_H $ and $\hat{s}_L < s_L$, in both states net foreign assets are lower. 
Again $ca_t=0$ when the state in $t-1$ and $t$ are the same. When $t-1$ is L and $t$ is H, then $\hat{ca}_t = \hat{s}_H - \hat{s}_L$ and vice versa. 
Finally, if the initial value of $b_0$ in this case was instead $b_L$, then consumption would be identical to the case characterized in questions 1-5 above. Why? Because of full insurance via complete markets. This means that we only get a differenct consumption allocation in this question because $b_0$ was not state contingent. 

