---
title: "Exercise 4.7"
subtitle: "Durable Consumption, I"
---
<a class="return-button" href="index.qmd">⬅ Return</a>

## Problem

Consider a SOE model with nondurable and durable consumption goods. Let $c_{N,t}$ denote consumption of nondurables in period $t$, and let $c_{D,t}$ denote purchases of durables in period $t$. The stock of durable consumer goods, denoted $s_t$, is assumed to evolve over time as

$$
s_t = (1-\delta) s_{t-1} + c_{D,t},
$$

where $\delta \in (0,1]$ denotes the depreciation rate of durable goods. Households have preferences over consumption $c_t$ of the form

$$
\sum_{t=0}^{\infty} \beta^t U(c_t),
$$

where $U$ is increasing in consumption and concave. Consumption $c_t$ is a composite of nondurable consumption and the service flow provided by the stock of consumer durables. Specifically, assume that

$$
c_t =
\left[
(1-\alpha)^{\frac{1}{\eta}} c_{N,t}^{1 - \frac{1}{\eta}} +
\alpha^{\frac{1}{\eta}} s_t^{1 - \frac{1}{\eta}}
\right]^{\frac{1}{1 - \frac{1}{\eta}}},
$$

where $\eta > 0$ and $\alpha \in (0,1)$.

Households have access to an internationally traded risk-free one-period bond, which pays the interest rate $r_t$ when held between periods $t$ and $t+1$. The relative price of durables in terms of nondurables is one. The household is subject to a borrowing limit that prevents it from engaging in Ponzi schemes. Output, denoted $y_t$, is produced with capital according to a production function of the form $y_t = F(k_t)$, where $k_t$ denotes physical capital. The capital stock evolves over time as

$$
k_{t+1} = (1 - \delta_k) k_t + i_t,
$$

where $i_t$ denotes investment in period $t$, and $\delta_k$ is the depreciation rate on physical capital. 


1. Describe  the household's  budget set.

2. State the optimization problem of the household.

3. Present the complete set of equilibrium conditions.

4. The interest rate is constant over time and equal to $r_t = r = \beta^{-1} -1$. Assume that up to period $-1$, the economy was in a steady state equilibrium in which all variables were constant and $d=\bar{d}>0$, where $d$ denotes net external debt in the steady state. Find the share of expenditures on durables in total consumption expenditures in the steady state in terms of the parameters $\delta$, $r$, $\alpha$, and $\eta$. Suggest a strategy for calibrating those four parameters.

5. Assume that in period $0$ the economy unexpectedly receives a positive income shock as a consequence of the rest of the world forgiving part of the country's net foreign debt. Assume that the positive income shock results in a 1 percent increase in the consumption of nondurables in period 0. Find the percentage increase in purchases of durables and in total consumption expenditures in period 0. Compare your answer to the one you would have obtained if all consumption goods were nondurable.

6. Continuing to assume that consumption of nondurables has increased by 1 percent, find the change in the trade balance in period 0 expressed as a share of steady-state consumption expenditures. Is the response of the trade balance countercyclical? Compare your findings to those you would have obtained if all consumption goods were nondurable. How much amplification is there due to the presence of durables?



## Answer

#### 1.

The household budget set consists in sequences $k_{t+1}$, $d_t$, $c_{N,t}$, $c_{D,t}$, $i_t$, $s_t$, $c_t$ satisfying 

$$
F(k_t) + d_t = (1+r_{t-1}) d_{t-1} + c_{N,t} + c_{D,t} + i_t \tag{1}
$$

$$
k_{t+1} = (1-\delta_k) k_{t} + i_t \tag{2}
$$

$$
c_t = \left[ (1-\alpha)^{\frac{1}{\eta}} c_{N,t}^{1-\frac{1}{\eta}} + \alpha^{\frac{1}{\eta}} s_t^{1-\frac{1}{\eta}} \right] ^{\frac{1}{1-\frac{1}{\eta}}}, \tag{3}
$$

$$
s_t = (1-\delta) s_{t-1} + c_{D,t}, \tag{4}
$$

$$
\mbox{some borrowing limit} \tag{5}
$$

#### 2.

In period $t$ the household chooses: $c_t$, $c_{N,t}$, $c_{D,t}$, $s_t$, $d_t$, $k_{t+1}$, and $i_t$ to 

$$
\max \sum_{t=0}^{\infty} \beta^t U(c_t), 
$$

subject to (1)-(5) given initial conditions $k_0$, $d_{-1}$, $s_{-1}$, and a time path for $r_t$. 

#### 3.

An equilibrium are sequences: $c_t$, $c_{N,t}$, $s_t$, $k_{t+1}$, $d_t$ satisfying for $t\ge0$: 

$$
\left(\frac{1-\alpha}{\alpha}\right)^{1/\eta} \left(\frac{c_{N,t}}{s_t}\right)^{-1/\eta} =\frac1{1-\left(\frac{1-\delta}{1+r_t}\right)} \tag{6}
$$

$$
F'(k_{t+1}) +1 - \delta_k = 1+r_t \tag{7}
$$

$$
F(k_t) + d_t = (1+r_{t-1}) d_{t-1} + c_{N,t} + (s_t - (1-\delta)s_{t-1}) + (k_{t+1} - (1-\delta_k)k_{t}) \tag{8}
$$

$$
U'(c_t) \frac{\partial c_t}{\partial c_{N,t}} =\beta (1+r_t) U'(c_{t+1}) \frac{\partial c_{t+1}}{\partial c_{N,t+1}} \tag{9}
$$

$$
c_t = \left[ (1-\alpha)^{\frac{1}{\eta}} c_{N,t}^{1-\frac{1}{\eta}} + \alpha^{\frac{1}{\eta}} s_t^{1-\frac{1}{\eta}} \right] ^{\frac{1}{1-\frac{1}{\eta}}}, \tag{10}
$$

and the borrowing limit, given $s_{-1}$, $k_0$, $d_0$, and the process $\{r_{t-1}\}$

#### 4.

The share of expenditures on durables is given by: 

$$
s_d = \frac{c_D}{c_D+c_N}= \frac{1}{1+\frac{c_N}{c_D}}
$$

In the steady state, $c_D = \delta s$. Using this in (6) we have

$$
\left(\frac{1-\alpha}{\alpha}\right)^{1/\eta}b\left(\frac{c_{N}}{1/\delta c_{D}}\right)^{-1/\eta}=\frac1{1-\left(\frac{1-\delta}{1+r}\right)}
$$

Solve for $\frac{c_N}{c_D}$

$$
\left(\frac{1-\alpha}{\alpha}\right)^{-1} \left(\frac{c_{N}}{1/\delta c_{D}}\right) =\left( \frac{1}{1-\left(\frac{1-\delta}{1+r}\right)}\right)^{-\eta}
$$

$$
\left(\frac{c_{N}}{ c_{D}}\right) = \left(\frac{1-\alpha}{\delta \alpha}\right) \left( \frac{1}{1-\left(\frac{1-\delta}{1+r}\right)}\right)^{-\eta}=\left(\frac{1-\alpha}{\delta \alpha}\right)\left(\frac{1+r}{r+\delta}\right)^{-\eta}
$$

The share is then 

$$
s_{d} = \frac{cd }{cn + cd } = \frac{1} {1+ \left( \frac{1-\alpha}{\delta \alpha} \right) \left( \frac{\delta+r} {1+r}\right)^{\eta} }
$$

Suppose there was no durability, that is, $\delta=1$, then the share of expenditures on type D good would just be given by $\alpha$. but if there is durability, $\delta<1$, then the share on purchases of type D  is either greater or less than $\alpha$ depending on the size of $\eta$. Rewrite the share as: 

$$
s_{d} =  \frac{\alpha} {\alpha + (1-\alpha) \frac1{\delta} \left( \frac{\delta+r}{1+r}\right)^{\eta} }
$$

Let $x =  \frac1{\delta }\left(\frac{\delta+r}{1+r}\right)^{\eta}$.

Then rewrite the share as: 

$$
s_{d} =  \frac{\alpha}{\alpha + (1-\alpha) x }
$$

Consider 

$$
\frac{\partial x}{\partial \delta} =x \left[ -\frac1{\delta} + \frac{\eta}{\delta+r} \right]
$$

Hence if we pick the elasticity of substitution between type D and type N goods high enough, namely such that $-\frac1{\delta} + \frac{\eta}{\delta+r}>00$ then the expenditure share is on type D goods is bigger than $\alpha$ for $\delta <1$.  

How to calibrate $\delta$, $r$, $\alpha$, $\eta$?

1.) The share of expenditures share of durables in total consumption is observable. So I would have this as one calibration restriction: 

2.) Then the interest rate $r$ should be observable. 

3.) Same for the rate of depreciation of durables, $\delta$. 

At this point I have 3 restrictions and 4 unknowns. Thus I am one short. 

The other steady state restrictions don't really pin down $\alpha$ and $\eta$ separately. 

Perhaps one could get information about $\eta$ from how different $c^N$ and $c^D$ respond to interest rate shocks. Using a log linearized version of equation (6) to identify $\eta$ and data on $r_t$, $c^N_t$, $c^D_t$ treating $s_t$ as latent.

#### 5.

Note that since the world interest rate does not change by equation (6) we have: 

$$
\hat{c}^N_t = \hat{s}_t
$$

Log-linearizing equation (4) we obtain: 

$$
\hat{s}_t = (1-\delta) \hat{s}_{t-1} + \delta \hat{c}^D_t
$$

In period 0, $\hat{s}_{-1}=0$ and hence we have that 

$$
\hat{c}^D_0 = \frac1{\delta} \hat{c}^N_0
$$

Suppose $\delta = 0.05$, then expenditures on durables rise ten times as much as expenditures on nondurables. 

Let $E_t$ denote total consumption expenditures: 

$$
E_t = c^N_t + c^D_t
$$

Log-linearizing this expression we obtain: 

$$
\hat{E} _t = \frac{c^N}{c^N + c^D} \hat{c}^N_t + \frac{c^D}{c^N + c^D} \hat{c}^D_t 
$$

and hence in period 0: 

$$
\hat{E} _0 = \frac{c^N + 1/\delta c^D}{c^N + c^D} \hat{c}^N_0
$$

So clearly because $\frac{c^N + 1/\delta c^D}{c^N + c^D}>1$ total expenditures go up by more than expenditures on nondurables. 

If all consumption goods are nondurable, $\delta=1$,  and hence $\frac{c^N + 1/\delta c^D}{c^N + c^D}=1$ implying that total consumption would have increased by the same as $c^N$. 

#### 6.

$$
tb_t = F(k_t) - i_t - c^N_t -c^D_t. 
$$

Linearize around $tb_t$ and the natural log of $c^N$, $c^D$. Note that the debt forgiveness shock leaves $k_0$, $i_0$ unchanged. Hence we have: 

$$
\frac{tb_0 - tb}{c^N + c^D}  = - \hat{E}_0 = - \frac{c^N + 1/\delta c^D}{c^N + c^D} \hat{c}^N_0
$$

The trade balance deteriorates. Is it countercyclical? Well output does not change, so there is a zero conditional correlation with GDP and the trade balance. 

How much amplification? Without durability,  $\delta=1$,  the trade balance would have fallen by one percent of total steady-state  consumption expenditures. With durability, $\delta<1$, the response of the trade balance is larger, $- \frac{c^N + 1/\delta c^D}{c^N + c^D}$. How much larger is it? Compute the difference in the absolute value of the coefficient on $\hat{c}^N_0$ for the case with durability and without durability, that is, 

$$
\frac{c^N + 1/\delta c^D}{c^N + c^D} - \frac{c^N + 1/1 c^D}{c^N + c^D} = \frac{(1-\delta)/\delta c^D }{c^N + c^D}= \frac{1-\delta}{\delta}   \frac{\alpha}{\alpha+(1-\alpha) x} = \frac{(1-\delta) \alpha}{\delta \alpha+(1-\alpha) \delta x}
$$

Replacing $x$ by its definition we have 

$$
\mbox{amplification}= \frac{\alpha(1-\delta)}{\alpha \delta +\left(\frac{\delta+r}{1+r}\right)^{\eta} (1-\alpha)} >0
$$

Amplification is highest when $\delta\rightarrow 0$. To see this note that $\partial{am}/\partial{\delta} <0$ for $0<\delta\le1$ 